Add Your Matt Holovach
wesbos/awesome-uses pull request #1002
Opened 2020-10-15 16:52 UTC by seoMattH

Added this third one down

{
    name: 'Matt Holovach',
    description: 'Loves SEO, improving coding skills and good food.',
    url: 'https://www.coloradoseodesign.com/',
    twitter: '@HolovachMatt'
    emoji: '🚀',
    country: 'USA',
    computer: 'microsoft',
    phone: 'android',
    tags: ['Developer', 'Alpine.js', 'PHP', 'JavaScript', 'CSS', 'Gulp', 'Perch CMS', 'HTML', 'Node.js'],
  }

2020-10-16 01:26 UTC, jorgeruvalcaba commented on src/data.js
> +    url: 'https://www.coloradoseodesign.com/',
This should direct to a uses page

2020-10-16 01:27 UTC, jorgeruvalcaba commented on src/data.js
> +    computer: 'microsoft',
this should be **microsoft**

2020-10-16 01:28 UTC, jorgeruvalcaba commented on src/data.js
> +    country: 'USA',
You should put usa emoji here

2020-10-16 01:28 UTC, jorgeruvalcaba commented on src/data.js
> +    description: 'Loves SEO, improving coding skills and good food.',
(optional) could you remove the dot at the end of the line?

2020-10-16 01:29 UTC, jorgeruvalcaba reviewed
Left some comments @seoMattH

2020-10-16 03:41 UTC, davidak requested changes
see comments

2020-10-20 15:04 UTC, davidak requested changes
@seoMattH thanks for updating the PR.

Can you accept my suggestions?

2020-10-20 15:04 UTC, davidak commented on src/data.js
> +    country: 'us',
```suggestion
    country: '🇺🇸',
```
this is the correct emoji

2020-10-20 15:04 UTC, davidak commented on src/data.js
> +    computer: 'microsoft',
@jorgeruvalcaba you mean

```suggestion
    computer: 'windows',
```

? it is `microsoft`, but that is wrong :D

2020-10-21 17:32 UTC, davidak approved these changes
Great, thank you!

2020-10-21 17:35 UTC, merged