I added me - Tim Smith
wesbos/awesome-uses pull request #1063
Opened 2020-12-30 01:00 UTC by timscodebase

2020-12-30 09:54 UTC, HugoDF requested changes

2020-12-30 09:54 UTC, HugoDF commented on src/data.js
> +    url: 'https://timsmith.tech/uses',
This 404s, in order for you to be added to awesome-uses, you'll need a working (& filled out) uses page

2021-01-02 19:57 UTC, timscodebase commented
I added my /uses page.  I did not before because I am in the process of creating a new site new-tim.netlify.app

2021-01-02 22:01 UTC, HugoDF approved these changes

2021-03-09 07:17 UTC, gatarelib requested changes

2021-03-09 07:17 UTC, gatarelib commented on src/data.js
> +    phone: 'iPhone',
`Error: "phone" must be one of [iphone, android, windowsphone, flipphone]`

2021-12-28 04:07 UTC, BlakeCampbells commented
Closing due to inactivity.

2021-12-28 04:07 UTC, closed without merging