Add Slim Ktari.
wesbos/awesome-uses pull request #1156
Opened 2021-04-21 22:15 UTC by slimktari

2021-04-26 00:55 UTC, gatarelib requested changes

2021-04-26 00:55 UTC, gatarelib commented on src/data.js
> +    url: 'http://slimktari.com/',
The url "http://slimktari.com/" fails to match the required pattern: /(use|uses|using|setup|environment|

2021-12-18 16:15 UTC, BlakeCampbells commented
Should we close due to inactivity?

2022-01-21 15:21 UTC, BlakeCampbells commented
Closing due to inactivity, @slimktari feel free to make another PR with the requested changes.

2022-01-21 15:22 UTC, closed without merging