🎉 add bineetNaidu
wesbos/awesome-uses pull request #1186
Opened 2021-06-10 04:52 UTC by bineetNaidu

2021-06-10 05:00 UTC, bineetNaidu commented
Can anyone tell what need to be fixed? :smiley:

2021-06-10 06:50 UTC, gatarelib requested changes

2021-06-10 06:50 UTC, gatarelib commented on src/data.js
> +    url: 'https://bineetnaidu.github.io/uses',
Error: Ping to "https://bineetnaidu.github.io/uses" failed with status: 404

2022-01-02 22:39 UTC, BlakeCampbells commented
Closing due to inactivity.

2022-01-02 22:39 UTC, closed without merging