Added @altsyset
wesbos/awesome-uses pull request #1256
Opened 2021-11-05 03:47 UTC by altsys

2021-11-07 16:44 UTC, gatarelib requested changes

2021-11-07 16:44 UTC, gatarelib commented on src/data.js
> +    country: 'ET',
For country, use  🇪🇹 not ET

2021-11-08 14:17 UTC, gatarelib requested changes

2021-11-08 14:17 UTC, gatarelib commented on src/data.js
> +    computer: 'Lenovo',
"computer" must be one of [apple, windows, linux, bsd]

2022-01-21 15:27 UTC, BlakeCampbells commented
Closing due to inactivity, @altsys feel free to make another PR with the requested changes.

2022-01-21 15:27 UTC, closed without merging