Add @adamrusted
wesbos/awesome-uses pull request #1379
Opened 2022-06-12 13:32 UTC by adamrusted

2022-06-12 21:45 UTC, BlakeCampbells requested changes
Hey @adamrusted will you update your URL to follow the format with one of the following:  ```use|uses|using|setup|environment```

2022-06-19 10:01 UTC, adamrusted commented
Yep - sorted!

2022-06-19 21:09 UTC, BlakeCampbells approved these changes

2022-06-19 21:09 UTC, BlakeCampbells commented
@adamrusted perfect thank you!

2022-06-19 21:09 UTC, merged