Adding Lasha Tatulashvili
wesbos/awesome-uses pull request #1384
Opened 2022-06-19 13:02 UTC by lashatatu

2022-06-19 21:15 UTC, BlakeCampbells requested changes
Hey @lashatatu will you please add a uses page to your website? Then we can get this merged in!

2022-06-20 02:52 UTC, lashatatu commented
update data.js with lashatatu.dev/uses 

added uses page.

2022-06-20 02:52 UTC, lashatatu commented
> Hey @lashatatu will you please add a uses page to your website? Then we can get this merged in!

update data.js with lashatatu.dev/uses

added uses page.

2022-06-20 12:15 UTC, BlakeCampbells approved these changes

2022-06-20 12:17 UTC, merged