Added Ihtisham Khan
wesbos/awesome-uses pull request #1461
Opened 2022-10-15 18:45 UTC by ihtishamKhan

2022-10-16 17:38 UTC, BlakeCampbells requested changes
I think your editor adjusted whitespace, will you make a clean PR please.

2022-10-17 06:53 UTC, ihtishamKhan commented
@BlakeCampbells Please have a look I have removed the indentations

2022-10-17 14:34 UTC, BlakeCampbells approved these changes

2022-10-17 14:35 UTC, BlakeCampbells approved these changes
Perfect, thank you!

2022-10-17 14:35 UTC, merged