Gurdeep Singh - Happy Hacking
wesbos/awesome-uses pull request #1680
Opened 2023-10-13 14:34 UTC by Gurdeep99

2024-05-22 10:56 UTC, jovyllebermudez commented
why you naming it like that super sus

2024-05-29 23:13 UTC, BlakeCampbells commented
> why you naming it like that super sus

It was probably for Hacktober Fest.

2024-05-29 23:14 UTC, BlakeCampbells requested changes

2024-05-29 23:14 UTC, BlakeCampbells commented on src/data.js
> +    url: 'https://www.gurdeep.net/uses',
Two changes:
- Make sure your uses page is live
- Make sure the country is the flag emoji instead of IN

2024-10-16 14:19 UTC, closed without merging