Add Noha Fahmi
wesbos/awesome-uses pull request #1689
Opened 2023-10-31 19:16 UTC by NohaFahmi

✅ I've read and understood the requirements

Add your name to verify: Noha Fahmi

2023-11-29 02:29 UTC, BlakeCampbells requested changes
Hey @NohaFahmi looks like your site is down, will you take a look and then re-request a review?

2024-01-02 11:26 UTC, gatarelib requested changes

2024-01-02 11:26 UTC, gatarelib commented on src/data.js
> +    url: 'https://nohafahmi.com/uses/',
The link seems not to work. Could you double-check.

2024-05-29 22:50 UTC, BlakeCampbells commented
Closing due to inactivity

2024-05-29 22:50 UTC, closed without merging