add Aaron Parecki
wesbos/awesome-uses pull request #1700
Opened 2023-12-30 22:02 UTC by aaronpk

2024-01-02 11:27 UTC, gatarelib approved these changes

2024-01-02 11:49 UTC, gatarelib requested changes

2024-01-02 11:49 UTC, gatarelib commented on src/data.js
> +    url: 'https://aaronparecki.com/life-stack/',
The link should be a `/uses` or `/use`

2024-05-29 22:50 UTC, BlakeCampbells commented
Closing due to inactivity

2024-05-29 22:50 UTC, closed without merging