Add Zachary Kai
wesbos/awesome-uses pull request #1821
Opened 2024-06-29 11:14 UTC by zacharykai

Add https://zacharykai.net/uses to uses.tech please.

2024-07-16 03:19 UTC, BlakeCampbells approved these changes

2024-07-16 03:19 UTC, BlakeCampbells approved these changes
Great color palette!

2024-07-16 03:22 UTC, BlakeCampbells requested changes
Sorry, I completely missed that country is a requirement. Will you add that when you get a chance?

2024-07-18 03:53 UTC, zacharykai commented
Did that work? Thank you for picking that up!

2024-07-21 05:08 UTC, merged