Add Dennis Mathenge
wesbos/awesome-uses pull request #927
Opened 2020-08-25 19:25 UTC by creativehubspace

2020-08-27 17:38 UTC, gatarelib reviewed
The page is yet to be populated with data I guess.

2020-08-27 18:00 UTC, creativehubspace commented
Working on it.

2020-09-12 09:36 UTC, creativehubspace commented
Added a few details to the page.

2020-09-27 11:02 UTC, davidak requested changes

2020-09-27 11:02 UTC, davidak commented on src/data.js
> +    twitter: '_dennisnm',
```suggestion
    twitter: '@_dennisnm',
```
this is probably needed to work

2020-09-27 12:47 UTC, creativehubspace commented on src/data.js
> +    twitter: '_dennisnm',
Twitter handle updated.

2020-09-27 15:19 UTC, davidak approved these changes
LGTM

2020-10-12 19:02 UTC, merged