Merge duplicate Node.js tags (Issue #637)
wesbos/awesome-uses pull request #962
Opened 2020-10-03 20:46 UTC by nico-bachner

2020-10-04 17:30 UTC, davidak approved these changes
looks good

only one typo

2020-10-04 17:30 UTC, davidak commented on src/data.js
> +      'node',
```suggestion
      'Node',
```
that would be a duplicate again

2020-10-06 17:38 UTC, HugoDF requested changes
Technically "Node.js" is the official spelling https://nodejs.org/en/

2020-10-06 17:56 UTC, nico-bachner commented
I used Node because it was the more popular name, but if it's ok, I'd be more than happy to change it to Node.js

2020-10-06 17:59 UTC, HugoDF commented
> I used Node because it was the more popular name, but if it's ok, I'd be more than happy to change it to Node.js

I'm not particularly fussy, but if the trademark is on Node.js then we should probably use that 

Also, I think this branch has conflicts that you'll need to resolve.

2020-10-07 12:37 UTC, nico-bachner commented
Should be all good now

2020-10-07 12:52 UTC, davidak approved these changes

2020-10-12 19:01 UTC, merged